### ISSUE TITLE
:bug:  端口突然停止监听

### ISSUE THREAD

**Issue by pysio2007** [TTB-Network/python-openbmclapi#54]
**问题描述**
端口停止监听后不重新启用

**问题重现**
重现问题的步骤：
长时间运行遇到的问题

**预期行为**
nginx 502 然后节点被踢下线

**截图**
```
[2024-04-29 18:56:50] [WARNING] [core.network:check_ports:209]: 端口 8080 已被关闭，正在重新开启……
[2024-04-29 18:56:50] [ERROR] [core.network:check_ports:213]: Traceback (most recent call last):
  File "/usr/lib64/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 1147, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 1180, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/bmclapi/python-openbmclapi/core/network.py", line 195, in check_ports
    await asyncio.wait_for(
  File "/usr/lib64/python3.12/asyncio/tasks.py", line 519, in wait_for
    async with timeouts.timeout(timeout):
  File "/usr/lib64/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

```

**运行环境**
RHEL9.3/Python 3.12.2

**Comment by tianxiu2b2t** [comment]
asyncio问题，目前已内置检测端口查活

**Comment by tianxiu2b2t** [comment]
并且这是客户端概率性问题，可能伴随CC攻击，如果长时间未启用，请提供日志
