### ISSUE TITLE
:bug: 保活时异常

### ISSUE THREAD

**Issue by sciencekiller** [TTB-Network/python-openbmclapi#69]
节点正常上线，出现反复地报错，均为以下内容
```shell
[2024-05-22 20:11:54] [ERROR] [core.cluster:_keepalive:752]: Traceback (most recent call last):
  File "/mnt/Python-OpenBMCLAPI/python-openbmclapi/core/cluster.py", line 719, in _keepalive
    if not get_hash_content(self.keepalive_file.hash, content):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Python-OpenBMCLAPI/python-openbmclapi/core/api.py", line 260, in get_hash_content
    h.update(content)
TypeError: object supporting the buffer API required
```

**Comment by tianxiu2b2t** [comment]
已修复
