### ISSUE TITLE
:bug: 在目录不存在时无法创建目录

### ISSUE THREAD

**Issue by xuzhichang** [TTB-Network/python-openbmclapi#70]
**问题描述**
目录不存在时只会报错，不会进行任何其他操作

**日志**
**日志**
[Config] update.auto_download is not set, does it exist?
[Config] certificate.cert is not set, does it exist?
[Config] certificate.key is not set, does it exist?
[2024-05-23 22:43:31] [INFO] [core:init:19]: 加载中……
[2024-05-23 22:43:31] [INFO] [core:init:21]: 当前 Python 版本：3.12.3。
[2024-05-23 22:43:31] [INFO] [core.cluster:__init__:355]: 当前文件检查模式：SIZE。
[2024-05-23 22:43:31] [INFO] [core.cluster:init:1391]: 当前总计有 1 个储存，0 个本地储存，1 个 WebDav 储存。
[2024-05-23 22:43:31] [INFO] [core.system:init:85]: 正在初始化系统信息统计……
[2024-05-23 22:43:31] [INFO] [plugins:load_plugins:58]: 准备加载插件中……
[2024-05-23 22:43:31] [INFO] [plugins:load_plugins:73]: 成功加载插件 [Example Plugin]！版本：[0.0.1]，作者：[tianxiu2b2t]。
[2024-05-23 22:43:31] [INFO] [plugins.example:enable:13]: This is an example plugin.
[2024-05-23 22:43:31] [ERROR] [core.certificate:_load_cert:22]: cert.error.failed.file（错误：无法找到该 i18n 字符串）
[2024-05-23 22:43:31] [INFO] [core.cluster:fetchToken:62]: 正在获取 token……
[2024-05-23 22:43:31] [INFO] [core.network:start:229]: 正在端口 8080 上监听服务器。
[2024-05-23 22:43:31] [SUCCESS] [core.cluster:fetchToken:91]: 成功获取 token。有效时长：24:00:00。
[2024-05-23 22:43:31] [SUCCESS] [core.cluster:_:1166]: 成功获取证书！到期时间：2024-08-03 07:59:59
[2024-05-23 22:43:31] [SUCCESS] [core.certificate:load_text:53]: 成功从本地文件中加载证书！
[2024-05-23 22:43:31] [INFO] [core.network:start:225]: 正在端口 8800 上监听 SSL 服务器。
[2024-05-23 22:43:31] [INFO] [core.network:start:229]: 正在端口 8080 上监听服务器。
[WebDav List Files <endpoint: '/download/download'>]: 0it [00:00, ?it/s]
[2024-05-23 22:43:34] [INFO] [core.cluster:get_files:169]: 成功获取文件列表！
[2024-05-23 22:43:35] [INFO] [core.cluster:get_files:175]: 文件数量：137.01k，文件最后修改时间：2024-05-23 17:32:12。
检查文件中: 100%|███████████████████████| 137k/137k [00:00<00:00, 180k 个文件/s]
[2024-05-23 22:43:36] [INFO] [core.cluster:__call__:536]: 文件缺失：137.01k。
[2024-05-23 22:43:36] [INFO] [core.cluster:__call__:541]: 下载配置策略：sync，下载源：openbmclapi，下载并发：5。
下载文件中:   0%|                          | 273k/127G [00:00<41:30:43, 911kb/s][2024-05-23 22:43:37] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/40/4052b7c2d0ed0184db75267f5368bc7028d8db53 not found

[2024-05-23 22:43:37] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：4052b7c2d0ed0184db75267f5368bc7028d8db53 (352.44KB) => 4052b7c2d0ed0184db75267f5368bc7028d8db53 (-1B)。
下载文件中:   0%|                         | 1.01M/127G [00:02<67:10:20, 563kb/s][2024-05-23 22:43:39] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/6a/6a780edf2f207b41a6fdea6cec0c25ec not found

[2024-05-23 22:43:39] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：6a780edf2f207b41a6fdea6cec0c25ec (38.66KB) => 6a780edf2f207b41a6fdea6cec0c25ec (-1B)。
[2024-05-23 22:43:39] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/7f/7f8cd234306369c48e7523ae81073e915f5a5584 not found

[2024-05-23 22:43:39] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：7f8cd234306369c48e7523ae81073e915f5a5584 (301.15KB) => 7f8cd234306369c48e7523ae81073e915f5a5584 (-1B)。
下载文件中:   0%|                        | 2.73M/127G [00:03<20:10:55, 1.87Mb/s][2024-05-23 22:43:40] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/02/02ad8c7dae8c7ee3407e5475ebff1df1313a3cea not found

[2024-05-23 22:43:40] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：02ad8c7dae8c7ee3407e5475ebff1df1313a3cea (72.65KB) => 02ad8c7dae8c7ee3407e5475ebff1df1313a3cea (-1B)。
[2024-05-23 22:43:41] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/64/64a872fc401af33ff07c3ffc2dd065ea not found

[2024-05-23 22:43:41] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：64a872fc401af33ff07c3ffc2dd065ea (12.06KB) => 64a872fc401af33ff07c3ffc2dd065ea (-1B)。
下载文件中:   0%|                        | 3.41M/127G [00:04<24:10:25, 1.56Mb/s][2024-05-23 22:43:41] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/21/21551c094193ab59d284b434c1e33a3ddf4b5c0e not found

[2024-05-23 22:43:41] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：21551c094193ab59d284b434c1e33a3ddf4b5c0e (2.36MB) => 21551c094193ab59d284b434c1e33a3ddf4b5c0e (-1B)。
下载文件中:   0%|                        | 4.03M/127G [00:05<32:22:08, 1.17Mb/s][2024-05-23 22:43:42] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/1d/1d321a482442e8239df86861556a2544380e2b0f not found

[2024-05-23 22:43:42] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：1d321a482442e8239df86861556a2544380e2b0f (137.5KB) => 1d321a482442e8239df86861556a2544380e2b0f (-1B)。
[2024-05-23 22:43:42] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/24/24b5a02d2fc1e9cfc7f71d79ecd49b72251708f4 not found

[2024-05-23 22:43:42] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：24b5a02d2fc1e9cfc7f71d79ecd49b72251708f4 (40B) => 24b5a02d2fc1e9cfc7f71d79ecd49b72251708f4 (-1B)。
下载文件中:   0%|                         | 8.90M/127G [00:07<7:42:47, 4.90Mb/s][2024-05-23 22:43:44] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/25/257ad9f50675f5c0af3f9dc06c973c65681894db not found

[2024-05-23 22:43:44] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：257ad9f50675f5c0af3f9dc06c973c65681894db (558.22KB) => 257ad9f50675f5c0af3f9dc06c973c65681894db (-1B)。
下载文件中:   0%|                        | 10.6M/127G [00:08<19:00:39, 1.99Mb/s][2024-05-23 22:43:45] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/97/977b2d26114030800e3306cdf3ae7c06 not found

[2024-05-23 22:43:45] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：977b2d26114030800e3306cdf3ae7c06 (40B) => 977b2d26114030800e3306cdf3ae7c06 (-1B)。
下载文件中:   0%|                        | 11.9M/127G [00:09<13:57:29, 2.71Mb/s][2024-05-23 22:43:46] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/58/58987cdfd00404ed1ffeb3bb2cb3d8b8 not found

[2024-05-23 22:43:46] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：58987cdfd00404ed1ffeb3bb2cb3d8b8 (25.91KB) => 58987cdfd00404ed1ffeb3bb2cb3d8b8 (-1B)。
下载文件中:   0%|                         | 14.8M/127G [00:09<7:48:58, 4.84Mb/s][2024-05-23 22:43:46] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/88/882fa5d1f9394a7b1e3bc534e621c8ef65d46210 not found

[2024-05-23 22:43:46] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：882fa5d1f9394a7b1e3bc534e621c8ef65d46210 (2.56MB) => 882fa5d1f9394a7b1e3bc534e621c8ef65d46210 (-1B)。
[2024-05-23 22:43:47] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/a9/a993d413f0754a3ffc2ceb805828c27329339f39 not found

[2024-05-23 22:43:47] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：a993d413f0754a3ffc2ceb805828c27329339f39 (394.0KB) => a993d413f0754a3ffc2ceb805828c27329339f39 (-1B)。
下载文件中:   0%|                        | 15.6M/127G [00:10<17:29:14, 2.16Mb/s][2024-05-23 22:43:47] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/66/6652bd7e8b57684d1958349fd691e0cf4ecefb7e not found

[2024-05-23 22:43:47] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：6652bd7e8b57684d1958349fd691e0cf4ecefb7e (331.17KB) => 6652bd7e8b57684d1958349fd691e0cf4ecefb7e (-1B)。
下载文件中:   0%|                        | 17.3M/127G [00:10<11:01:37, 3.43Mb/s][2024-05-23 22:43:47] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/1c/1ca93368146faec9135218d13579fca940265faf not found

[2024-05-23 22:43:47] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：1ca93368146faec9135218d13579fca940265faf (79.44KB) => 1ca93368146faec9135218d13579fca940265faf (-1B)。
下载文件中:   0%|                        | 18.2M/127G [00:11<10:09:38, 3.72Mb/s][2024-05-23 22:43:48] [ERROR] [core.cluster:_mount_file:306]: Traceback (most recent call last):
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 302, in _mount_file
    r = await storage.write(file.hash, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 931, in write
    await self._execute(self.session.upload_to(io.getbuffer(), path))
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 778, in _execute
    raise e
  File "/home/jensenxu123/下载/python-openbmclapi-master/core/cluster.py", line 759, in _execute
    return await asyncio.wait_for(target, timeout=WEBDAV_TIMEOUT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 71, in _wrapper
    res = await res
          ^^^^^^^^^
  File "/home/jensenxu123/.local/lib/python3.12/site-packages/aiowebdav/client.py", line 531, in upload_to
    raise RemoteParentNotFound(urn.path())
aiowebdav.exceptions.RemoteParentNotFound: Remote parent for: /download/download/a3/a31587dff13eea95b729e142111c57475556fe08 not found

[2024-05-23 22:43:48] [ERROR] [core.cluster:_mount_file:311]: 在尝试下载文件时出错：无法复制文件：a31587dff13eea95b729e142111c57475556fe08 (403.45KB) => a31587dff13eea95b729e142111c57475556fe08 (-1B)。
^C[2024-05-23 22:43:48] [INFO] [core.statistics:exit:282]: 正在保存 [0] 统计中
[2024-05-23 22:43:48] [SUCCESS] [core.statistics:exit:287]: 成功保存统计
下载文件中:   0%|                        | 18.8M/127G [00:11<22:46:46, 1.66Mb/s]
[2024-05-23 22:43:48] [SUCCESS] [core:exit:70]: 成功退出！

**Comment by tianxiu2b2t** [comment]
请提供路径和当时目录的情况

**Comment by xuzhichang** [comment]
当时的目录是这样的：
没有/download文件夹
更没有/downlaod/download文件夹
但是程序也没有创建父文件夹

**Comment by SilianZ** [comment]
应该使用 `exists()` 函数来检测文件夹是否存在。
