### ISSUE TITLE
🐛 主控偶尔无法正确测速

### ISSUE THREAD

**Issue by Dongyanmio** [TTB-Network/python-openbmclapi#92]
### 在开始之前……

- [X] 我已在 [Issue](https://github.com/TTB-Network/python-openbmclapi/issues) 中搜索过我的要上报的漏洞，确定没有人提出过此漏洞。
- [X] 我是用的是最新的 [Release 版本](https://github.com/TTB-Network/python-openbmclapi/releases/latest)而不是最新的 [master 分支](https://github.com/TTB-Network/python-openbmclapi/tree/master)。

### 问题描述

在使用 python-openbmclapi 测试我的主控时，发现在节点端发送 enable 请求等待测速时，主控无法正常测速，而节点端也会报错。

### 问题重现

1. 打开程序
2. 等待下载文件
3. 等待发送 enable 请求
4. 等待测速时的报错

### 运行环境

Python 版本: 3.12.2
系统: Windows 11
主控: iodine-at-home
分发的文件大小和: 110MB

### 节点类型

全量

### 运行日志或截图

```shell
[2024-08-04 14:59:56] [SUCCESS] [core.cluster:start_check:1052]: 成功下载所有文件。耗时：03:39
[2024-08-04 14:59:56] [DEBUG] [core.cluster:socketio_emit_with_ack:866]: 发送数据：enable {'host': 'home.zeroctagon.top', 'port': 11451, 'byoc': True, 'version': '1.11.0', 'noFastEnable': True, 'flavor': {'runtime': 'python/3.12.2 v1.2.2', 'storage': 'file', 'total': 1, 'file': 1, 'webdav': 0}}。
[2024-08-04 14:59:56] [DEBUG] [socketio.async_client:emit:222]: Emitting event "enable" [/]
[2024-08-04 14:59:56] [DEBUG] [engineio.async_client:_send_packet:424]: Sending packet MESSAGE data 21["enable",{"host":"home.zeroctagon.top","port":11451,"byoc":true,"version":"1.11.0","noFastEnable":true,"flavor":{"runtime":"python/3.12.2 v1.2.2","storage":"file","total":1,"file":1,"webdav":0}}]
Traceback (most recent call last):
  File "G:\python-openbmclapi\core\web.py", line 1324, in handle
    await resp(request, client)
  File "G:\python-openbmclapi\core\web.py", line 825, in __call__
    content.write(data)
TypeError: a bytes-like object is required, not 'Response'
[2024-08-04 15:00:02] [DEBUG] [engineio.async_client:_receive_packet:404]: Received packet PING data
[2024-08-04 15:00:02] [DEBUG] [engineio.async_client:_send_packet:424]: Sending packet PONG data
[2024-08-04 15:00:04] [DEBUG] [engineio.async_client:_receive_packet:404]: Received packet MESSAGE data 31[[{"message":"\u9519\u8bef: "}]]
[2024-08-04 15:00:04] [DEBUG] [socketio.async_client:_handle_ack:404]: Received ack [/]
[2024-08-04 15:00:04] [DEBUG] [core.cluster:callback:880]: 接收数据：enable [{'message': '错误: '}, None]。
[2024-08-04 15:00:04] [ERROR] [core.cluster:cluster_enable:594]: 无法启动服务：错误:
[2024-08-04 15:00:04] [INFO] [core.cluster:cluster_retry:554]: 将在 60 秒后重试。
```

### 备注

![d2d17b85faad9928cd2f5644770cecd8](https://github.com/user-attachments/assets/2a457c2e-b8b4-4866-849f-2a4f5ec0a47a)

### 如果……

- [x] 如果可以的话，我可以帮助或自行修复这个漏洞。

**Comment by Dongyanmio** [comment]
查清了，我主控计算sign的问题，对不起

**Comment by tianxiu2b2t** [comment]
当主控的sign计算错误时候，则python端的测试会返回一个Response对象并且不被支持

**Comment by tianxiu2b2t** [comment]
此python端版本影响：v2以往的版本（不包括v2）

**Comment by tianxiu2b2t** [comment]
此 issue 未有任何消息，已关闭
